Add SetFlipVerticallyOnLoad method
Tom94/stbi-sharp pull request #4
Opened 2020-11-04 00:16 UTC by jchand99

- Adds SetFlipVerticallyOnLoad method that wraps stbi_set_flip_vertically_on_load function from stb_image.h
  - Static function within Stbi class

Usage:
```c#
Stbi.SetFlipVerticallyOnLoad(true);
```

2020-11-04 00:21 UTC, peppy requested changes
Just a tiny comment change for consistency, looks good otherwise!

2020-11-04 00:21 UTC, peppy commented on stbi-sharp.cs
> +        /// flip the image vertically, so the first pixel in the output array is the bottom left
```suggestion
        /// Flip the image vertically, so the first pixel in the output array is the bottom left.

```

2020-11-04 00:43 UTC, jchand99 commented on stbi-sharp.cs
> +        /// flip the image vertically, so the first pixel in the output array is the bottom left
Awesome! Thank you!

2020-11-04 00:45 UTC, peppy approved these changes

2020-11-05 07:39 UTC, Tom94 commented
I am mentally debating whether to expose STBI's stateful API or whether to instead add an optional parameter `bool flipVertically` to all the loading functions. I have a strong dislike for stateful APIs (just look at OpenGL :p) and STBI currently only has 2 state parameters, where the other one (unpremultiplying of alpha on iPhone pngs) arguably never should be touched.

Any opinions?

2020-11-05 08:41 UTC, peppy commented
Given there's only two, and they sound like toggles you'd *probably* only change state of once during execution (in *most* use cases) I think it's fine to be exposed as the native API. But honestly either would work. The argument for doing it as stateful API is one (or two) less extern calls...

Quite neutral though.

2020-11-05 14:39 UTC, jchand99 commented
When I was writing this change, I also went back and forth a bit on whether I wanted to add a flag to each of the functions, but decided against it because based on the way I was thinking to implement the flag, it added more conditional logic that was duplicated across each of the load methods. Because of this I decided just to expose the native API since it was less code. Also, as @peppy mentioned, the state changes most likely would be changed only once during runtime in *most* cases. I think that having the two states exposed as static methods in the Stbi class is fine, but either way would work and I would be willing to use either option, just personal preference really.

Side note: Ofc, the logic for the flag could be extracted to a function that would be called per load method, but the logic would still be run across each load method.

2020-11-06 06:45 UTC, merged

2020-11-06 06:47 UTC, Tom94 commented
That's fair. Gonna hold off from doing anything overcomplicated and stick as closely as possible to the native API. Thanks. :)